name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: zip -r module.zip * -x "*.git*"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            module.json
            module.zip
